import type { CSSProperties } from 'react';

export const browserPrinciplesTheme = {
  '--kp-hero-border': '#bfdbfe',
  '--kp-hero-radial-1': 'rgba(59, 130, 246, 0.15)',
  '--kp-hero-radial-2': 'rgba(14, 165, 233, 0.12)',
  '--kp-hero-bg': '#f7fbff',
  '--kp-eyebrow-border': '#bfdbfe',
  '--kp-eyebrow-bg': '#eff6ff',
  '--kp-eyebrow-text': '#1d4ed8',
  '--kp-signal-border': '#bfdbfe',
  '--kp-signal-bg': '#eff6ff',
  '--kp-signal-text': '#1d4ed8',
  '--kp-answer-border': '#bfdbfe',
  '--kp-answer-bg': '#eff6ff',
  '--kp-explain-border': '#bbf7d0',
  '--kp-explain-bg': '#f0fdf4',
  '--kp-code-accent': '#93c5fd',
  '--kp-tag-border': '#bfdbfe',
  '--kp-tag-bg': '#eff6ff',
  '--kp-tag-text': '#1d4ed8',
  '--kp-button-border': '#93c5fd',
  '--kp-button-text': '#1d4ed8',
  '--kp-button-hover': '#eff6ff',
} as CSSProperties;

export const engineeringTheme = {
  '--kp-hero-border': '#c4b5fd',
  '--kp-hero-radial-1': 'rgba(124, 58, 237, 0.12)',
  '--kp-hero-radial-2': 'rgba(99, 102, 241, 0.12)',
  '--kp-hero-bg': '#fbfaff',
  '--kp-eyebrow-border': '#ddd6fe',
  '--kp-eyebrow-bg': '#f5f3ff',
  '--kp-eyebrow-text': '#6d28d9',
  '--kp-signal-border': '#ddd6fe',
  '--kp-signal-bg': '#f5f3ff',
  '--kp-signal-text': '#6d28d9',
  '--kp-answer-border': '#c4b5fd',
  '--kp-answer-bg': '#f5f3ff',
  '--kp-explain-border': '#bfdbfe',
  '--kp-explain-bg': '#eff6ff',
  '--kp-code-accent': '#a78bfa',
  '--kp-tag-border': '#ddd6fe',
  '--kp-tag-bg': '#f5f3ff',
  '--kp-tag-text': '#6d28d9',
  '--kp-button-border': '#a78bfa',
  '--kp-button-text': '#6d28d9',
  '--kp-button-hover': '#f5f3ff',
} as CSSProperties;

export const scenarioTheme = {
  '--kp-hero-border': '#fcd34d',
  '--kp-hero-radial-1': 'rgba(245, 158, 11, 0.14)',
  '--kp-hero-radial-2': 'rgba(249, 115, 22, 0.12)',
  '--kp-hero-bg': '#fffaf2',
  '--kp-eyebrow-border': '#fde68a',
  '--kp-eyebrow-bg': '#fffbeb',
  '--kp-eyebrow-text': '#b45309',
  '--kp-signal-border': '#fde68a',
  '--kp-signal-bg': '#fffbeb',
  '--kp-signal-text': '#b45309',
  '--kp-answer-border': '#fcd34d',
  '--kp-answer-bg': '#fffbeb',
  '--kp-explain-border': '#bfdbfe',
  '--kp-explain-bg': '#eff6ff',
  '--kp-code-accent': '#f59e0b',
  '--kp-tag-border': '#fde68a',
  '--kp-tag-bg': '#fffbeb',
  '--kp-tag-text': '#b45309',
  '--kp-button-border': '#fbbf24',
  '--kp-button-text': '#b45309',
  '--kp-button-hover': '#fff7db',
} as CSSProperties;

export const reactInterviewTheme = {
  '--kp-hero-border': '#86efac',
  '--kp-hero-radial-1': 'rgba(34, 197, 94, 0.14)',
  '--kp-hero-radial-2': 'rgba(16, 185, 129, 0.12)',
  '--kp-hero-bg': '#f6fff9',
  '--kp-eyebrow-border': '#bbf7d0',
  '--kp-eyebrow-bg': '#f0fdf4',
  '--kp-eyebrow-text': '#15803d',
  '--kp-signal-border': '#bbf7d0',
  '--kp-signal-bg': '#f0fdf4',
  '--kp-signal-text': '#15803d',
  '--kp-answer-border': '#86efac',
  '--kp-answer-bg': '#f0fdf4',
  '--kp-explain-border': '#bfdbfe',
  '--kp-explain-bg': '#eff6ff',
  '--kp-code-accent': '#22c55e',
  '--kp-tag-border': '#bbf7d0',
  '--kp-tag-bg': '#f0fdf4',
  '--kp-tag-text': '#15803d',
  '--kp-button-border': '#4ade80',
  '--kp-button-text': '#15803d',
  '--kp-button-hover': '#ecfdf3',
} as CSSProperties;

export const vueInterviewTheme = {
  '--kp-hero-border': '#6ee7b7',
  '--kp-hero-radial-1': 'rgba(16, 185, 129, 0.14)',
  '--kp-hero-radial-2': 'rgba(5, 150, 105, 0.12)',
  '--kp-hero-bg': '#f5fffb',
  '--kp-eyebrow-border': '#a7f3d0',
  '--kp-eyebrow-bg': '#ecfdf5',
  '--kp-eyebrow-text': '#047857',
  '--kp-signal-border': '#a7f3d0',
  '--kp-signal-bg': '#ecfdf5',
  '--kp-signal-text': '#047857',
  '--kp-answer-border': '#6ee7b7',
  '--kp-answer-bg': '#ecfdf5',
  '--kp-explain-border': '#bfdbfe',
  '--kp-explain-bg': '#eff6ff',
  '--kp-code-accent': '#10b981',
  '--kp-tag-border': '#a7f3d0',
  '--kp-tag-bg': '#ecfdf5',
  '--kp-tag-text': '#047857',
  '--kp-button-border': '#34d399',
  '--kp-button-text': '#047857',
  '--kp-button-hover': '#e7fdf2',
} as CSSProperties;
